# Generated by Django 3.2.8 on 2021-11-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
